build.sh
Hi,
Also, I've create the tile38 port for FreeBSD platform: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=210147
And test iе щт various active FreeBSD version. Looks like all fine. It would be nice to mention the possibility of using your product on FreeBSD platform with installing from packages:
~~~
pkg install tile38
~~~
or from the ports:
~~~
make -C /usr/ports/databases/tile38 install
~~~
or via curl as usual for other OSes, when package tile38-1.2.0-freebsd-amd64.zip will be done
=> Add FreeBSD packaging. Tested on FreeBSD 10,11 x86_64

.gitignore
Hi,
VS Code is adding a '.vscode' folder to the source folder. This folder should be added to .gitignore.
=> Ignore VS Code folder

geojson/bbox.go
This patch fixes #64 by removing ```geo.DestinationPoint()``` from ```geojson.BBoxesFromCenter()``` and replacing it with a new function called ```geojson.BBoxBounds()``` that conforms to (the related sections of) http://janmatuschek.de/LatitudeLongitudeBoundingCoordinates#Latitude
If performance near the wraparound proves to be an issue, I or someone else can refactor, as mentioned in commented code inside of ```geojson.BBoxBounds()```.
=> Fix incorrect query boundaries when using large radii

controller/endpoint/endpoint.go, controller/endpoint/redis.go
Resolving #108 (Redis enpoint for webhooks)
**Redis**
The `redis://` provides support for sending messages to **Redis** *PUBSUB* channels.  
For example:
```redis
SETHOOK warehouse disque://10.0.20.78:6379/warehouse
```
All webhook messages should be send to the Redis server at 10.0.20.78:6379 in a [PUBSUB](https://redis.io/commands#pubsub) queue to a **warehouse** channel.
=> Redis endpoint for webhooks

.gitignore, cmd/tile38-server/main.go, controller/controller.go, controller/server/server.go, tests/mock_test.go
Simple **HTTP** & **WebSocket** transport disabling by using:
```bash
./tile38-server --http-transport false
```
Resolving: #92 
@tidwall need your review.
=> Disable HTTP & WebSocket transports on demand.

controller/endpoint/http.go
We faced problems with leaking http connections. We receive hooks by http, all connections are keep-alived. After few hours of our testing we noticed that we\`ve got ~400 opened connections despite of hardcoded limit to 20. Also we had same number of goroutines both on server & client sides. 
Default http client runs standalone goroutine for every connection so code in `Expired` doesn\`t close these connections it just set client to `nil`. And new created client opens and runs new goroutines for new connection.
=> Fix leaking http connections

controller/endpoint/http.go
Client can be created once in constructor so mutex isn`t required anymore.
=> remove mutex from HTTP endpoint

docker/Dockerfile
Just trying out Tile38 for the first time, and liking it.
I'm used to using `redis-cli` in the Redis image, and `psql` in the Postgres image, so I was surprised to not find `tile38-cli` in the Tile38 image. Could we add it?
=> Include tile38-cli in Docker image

pkg/core/gen.sh
Make was failing for me on linux.  With these changes things seem to work on both linux and mac.
=> Fix pkg/core/gen.sh so that make works on linux

.travis.yml, Makefile, build.sh, docker/Dockerfile
This PR contains:
* Automatic version detection by using git tags
* Fix for the Makefile (double package target)
* Enable Travis CI to build the Docker images and push to Docker Hub
* You'll need to set up the `DOCKER_USER` and `DOCKER_PASSWORD` environment variables in the Travis CI project/repo as described in https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
* Logic for Docker image tags is:
* If the push refers to a git tag, the Docker image tag will be the git tag
* If the push is on master, it will get pushed to the `edge` Docker image tag
* `latest will àlways refer to the last created git tag
What I noticed is that the Docker images build via Travis will trigger an error when being started, because ther's apparently a problem in the …
=> CI improvements

pkg/endpoint/endpoint.go
The current AMQP endpoint code does not allow RabbitMQ namespaces as it separates the queue from the URI via a "/" character.  The URI, however, should take allow a "/" within it to handle namespaces.  This is a very frustrating bug because the error message coming back from a server expecting a namespace is often cryptic or looks like an authentication error.
This PR checks if there are three elements to the endpoint: <uri>/<namespace>/<queue> and corrects the URI accordingly.
=> Fix AMQP and AMQPS webhook endpoints to support namespaces.

cmd/tile38-cli/main.go
when I hit Ctrl-D, I mean to exit, rather than to see the annoying "Error reading line: EOF"
=> handle Ctrl-D

pkg/geojson/poly/poly.go
Every developer trips on lat-lon vs. lon-lat at least once, so it's better to clarify this.
=> documentation: Point is [lat lon z]

internal/server/stats.go
Would you rather have a `version` or `server_version` in the output?
=> Add server command for `version` - closes #384

internal/endpoint/endpoint.go, internal/endpoint/kafka.go
Kafka endpoints would produce messages without a key. This ment that kafka message partitioning was random.
With the key we can make sure that events from the same key and id go to the same partition.
Unfortunately the the endpoint directly gets the message as bytes/string, so there is no way around parsing the json to cherry pick the data needed.
=> Kafka message key for each message based on key and id

Dockerfile
Resolves https://github.com/tidwall/tile38/issues/392. 1.12.0 had a wildly different Dockerfile which did include the CA-certs install. This change adds them to the new alpine image.
=> ca-certs in docker image

internal/server/scripts.go
Based on #411 server command is not available in Lua scripts. This PR add server command in Lua scripts.
=> Adds Server command for Lua scripts.

internal/server/aof.go, internal/server/aofshrink.go, internal/server/follow.go, internal/server/server.go
The AOF buffer can occasionally grow very large, which is OK, but the memory should be occasionally released.
=> Release aof buffer periodically

cmd/tile38-server/main.go
A SIGHUP should not kill the process.  `kill -SIGHUP <pid>` should gracefully be ignored.
More details at https://github.com/tidwall/tile38/issues/418#issuecomment-472009607
=> Ignore SIGHUP signals

internal/log/log.go
fixes for x1b[31m[FATA] output
=> log: fix typo in Fatalf func

tests/keys_search_test.go
Related to #453 - added RESP output tests of fields results for NEARBY and WITHIN searches ... for sanity's sake.
=> Added RESP output fields test for NEARBY/WITHIN

internal/server/stats.go
Load testing revealed that the Tile38 process dumped with high concurrency due to concurrent access to the connections map.
Added RLock/RUnlock around that access and re-tested.
=> Added RLock on connections map

internal/endpoint/mqtt.go
Each mqtt hook establishes separate connection to the MQTT broker. If
their clientIds are all equal the MQTT broker will disconnect the clients - the
protocol does not allow 2 connected clients with the same name
=> MQTT clientId should be unique

internal/server/json.go, internal/server/json_test.go, tests/json_test.go
This PR adds a new function that validates if a string is a number according to the JSON spec, replacing the call to ParseFloat. This fixes #493
This is my first experience with Go, so please let me know if I did something wrong, or if there is a more idiomatic way of doing things.
=> Strictly check if values passed to JSET are numbers

internal/server/stats_cpu.go
Fixes " Fprintf format %.2f has arg 0 of wrong type int" error when running tests on Windows
=> Fix fprintf type error in stats_cpu.go for non-linux/darwin builds

internal/server/follow.go
We encountered the following crash, this PR should fix
fatal error: concurrent map iteration and map write
goroutine 6756 [running]:
runtime.throw(0xd48942, 0x26)
/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc000dbced8 sp=0xc000dbcea8 pc=0x42d722
runtime.mapiternext(0xc000dbd030)
/usr/local/go/src/runtime/map.go:860 +0x597 fp=0xc000dbcf60 sp=0xc000dbced8 pc=0x40efa7
github.com/tidwall/tile38/internal/server.(*Server).cmdReplConf(0xc000364000, 0xc7b2a1dc20, 0xc0005a2000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/tmp/tile38.t7dy/go/src/github.com/tidwall/tile38/internal/server/follow.go:124 +0x3cc fp=0xc000dbd0a0 sp=0xc000dbcf60 pc=0xb1700c
github.com/tidwall/tile38/internal/server.(*Server).command(0xc000364000, 0xc7b2a1dc20, 0xc0005a2000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...) …
=> Fix a concurrent write/read on the server conn map

internal/clip/clip_test.go, internal/clip/polygon.go
Add a test for skipping empty rings.
This fixes https://github.com/tidwall/tile38/issues/542
=> Skip empty rings when clipping polygons.

internal/server/fence.go
Stack trace when tiles38-server crashed:
```
panic: runtime error: index out of range [1] with length 1
goroutine 19 [running]:
github.com/tidwall/tile38/internal/server.fenceMatchRoam(0xc0000b0a00, 0xc00020d180, 0xc00027c340, 0x7, 0xedf880, 0xc0004ef020, 0xedf880, 0xc000155b20, 0xedf880, 0xc00049d660, ...)
/home/larsw/go/src/github.com/larsw/tile38/internal/server/fence.go:413 +0x4f8
github.com/tidwall/tile38/internal/server.fenceMatch(0x0, 0x0, 0xc0001d7380, 0xc00020d180, 0x0, 0x0, 0x0, 0xc00015cb40, 0xc0005519c8, 0x4e1141, ...)
/home/larsw/go/src/github.com/larsw/tile38/internal/server/fence.go:100 +0x15e1
github.com/tidwall/tile38/internal/server.FenceMatch(0x0, 0x0, 0xc0001d7380, 0xc00020d180, 0x0, 0x0, 0x0, 0xc00015cb40, 0x4806c3, 0xc00027c700, ...) …
```
=> Fix crash in fenceMatchRoam causing an index out of range panic

internal/server/crud.go
=> limit hash precision to 12, not 64

internal/endpoint/endpoint.go, internal/endpoint/kafka.go
As [discussed](https://tile38.slack.com/archives/C0M6QN8VC/p1613396062034300), I added the option to enable TLS on the kafka endpoints and allowing to pass the required certificates similar to your `mqtt` approach.
As a failed connection due to false certificates does not show up in your Kafka broker, I added the option to debug TLS through saramas logger. I would love to make it work in the similar schema as your logging, but I frankly don't know how I would be doing that.
For easier debugging I also opted to use a different sarama.ClientID as the current default value of `sarama`. 
To reproduce my test environment you can create your keystore and truststore following this [bash script](https://github.com/confluentinc/cp-docker-images/blob/5.2.1-post/examples/kafka-cluster-ssl/secrets/cre …
=> add kafka tls config

internal/server/fence.go, internal/server/scanner.go, internal/server/search.go, tests/keys_search_test.go
addressing #599 
Now correctly shows distance in response, if point and object share the same coordinates without affecting `writeObject` return value for other searches.
For this to work I had to introduce a new type `Distance` whos `ready` property is only set in a nearby search. This way I can check its state in `writeObject` and will only append `distance` when it's `ready: true`.
I also added tests, to make sure it behaves as planned and does no affect the other searches and fences.
wdyt?
=> fix: return distance if point and object have the same coordinates

cmd/tile38-server/main.go, core/options.go
As you mentioned in the slack channel threads flag is deprecated so I think adding a deprecation warning would be helpful.
=> Deprecation warning for threads flag

internal/server/server.go, internal/server/stats.go
Returns 'ok' if the server is the leader or a follower with
a 'caught up' log.
This is mainly for HTTP connections that are using an
orchestration environment like kubernetes, but will work as a
general RESP command.
For HTTP a '200 OK' for 'caught up' and
'500 Internal Server Error' otherwise.
See #608
=> Added HEALTHZ command

internal/endpoint/kafka.go, internal/server/aof.go, internal/server/aofshrink.go, internal/server/server.go
This commit addresses an issue where the sarama kafka library
leaks memory when a connection closes unless the metrics
configuration that was passed to new connection is also closed.
#613
=> Kafka memory leak

internal/server/aof.go, internal/server/aofshrink.go, internal/server/server.go
This PR addresses an issue #449 where AOFSHRINK was modifying the aof metadata while there was more than one opened file handle. 
Which is a no-no on Windows.
=> Close follower files before finishing aofshrink

internal/server/scanner.go, internal/server/scanner_test.go, internal/server/token.go, tests/keys_test.go
The following optimizations were made:
* use copy() instead of a loop for copying array values;
* use array of values instead of a map for whereins;
* map the field names to index values once per-query, not per point.
The benchmark shows improvement (had to time 100 calls to have reliable data):
```
name          old time/op    new time/op    delta
FieldMatch-4    2.69µs ± 3%    1.53µs ± 5%  -43.02%  (p=0.000 n=9+10)
```
=> Optimize field match.

internal/collection/collection.go, internal/collection/collection_test.go, internal/server/scanner.go, internal/server/search.go, tests/keys_search_test.go, tests/mock_test.go, tests/tests_test.go
The current KNN implementation has two areas that can be improved:
- The current behavior is somewhat incorrect. When performing a kNN
query, the current code fetches k items from the index, and then sorts
these items according to Haversine distance. The problem with this
approach is that since the items fetched from the index are ordered by
a Euclidean metric, there is no guarantee that item k + 1 is not closer
than item k in great circle distance, and hence incorrect results can be
returned when closer items beyond k exist.
- The secondary sort is a performance killer. This requires buffering
all k items (again...they were already run through a priority queue in
the index), and then a sort. Since the items are mostly sorted, and
Go's sort implementation is a quickSort this is the worst …
=> Improve kNN behavior

internal/endpoint/endpoint.go, internal/endpoint/kafka.go
Hi! 👋 
in #615 we added authentication with SASL and shortly after the release I noticed that we did take care of the authentication but forgot about SSL in the process. As a result SASL authentication currently does only work if the connection to the broker is not encrypted (SASL PLAIN). This is because Tile38 does not allow for the verification to be skipped in the sarama config. 
I created an example for the case at [iwpnd/tile-kafka-sasl](https://github.com/iwpnd/tile38-kafka-sasl) and tested SASL auth without SSL successfully.
Now with this PR I want to fix this introducing a new auth flow to support TLS, SASL, SASL/SSL and no-auth as follows:
**SASL PLAIN**
`?auth=sasl&sha512=true` is using using credentials from the env `KAFKA_PASSWORD` / `KAFKA_USERNAME`
**SASL/SSL** …
=> kafka authentication methods

Dockerfile
Use a more current version of Alpine.
Version 3.8 is no longer supported by e.g. [Trivy](https://aquasecurity.github.io/trivy)
=> Upgrade alpine in Dockerfile

internal/server/config.go, internal/server/stats.go
PR for enhancement: https://github.com/tidwall/tile38/issues/642
Allow setting slave_priority in the config to any integer value greater than or equal to zero.
Zero means the slave will never be promoted to master(leader), and any other positive numeric value will be used as the priority order for Sentinel slave election when the master goes down.
If not specified the default priority of a slave is 100. If a negative number is specified then slave_priority will not be output in the INFO response and that slave will be considered to have the default priority value of 100.
=> Issue #642 - Expose config and INFO response for slave_priority

internal/server/scripts.go, tests/scripts_test.go
This PR resolves #630.
- Modified `lua.NewState()` call to open **only** the following modules:
* base\*
* table
* math
* string
* os\*
> \* Only opens `base.tonumber()`, `base.tostring()`, `os.clock()`, and `os.difftime()`.
- Vendored internal Lua function implementations for the subset functions from `gopher-lua` (required to open the subsets, otherwise entire module is available).
- Added `scripts_VULN_tests` into `tests/scripts_test.go`; tests for function existence.
All tests pass using go version 1.19.3 on Linux.
=> Prevent certain Lua modules/functions from loading

cmd/tile38-server/main.go
Graceful shutdown was implemented in this commit https://github.com/tidwall/tile38/commit/906824323b908790cdb7b3d26e80cd944536c5c7 but there is no way to trigger it from outside. This change makes SIGTERM trigger the graceful shutdown.
=> Add graceful shutdown on SIGTERM

cmd/tile38-cli/main.go
add support to env variables for tile38-cli, including password.
especially useful when running on docker, connecting to a protected server
=> add hostname, port, output, and password env variables to tile38-cli

internal/endpoint/amqp.go, scripts/build.sh
as discussed in #606, under some circumstances queues and bindings under AMQP should not be created. Disabled this for type 'topic'.
Cheers
Uwe
=> only create AMQP queue and binfings for non-topic exchanges

internal/endpoint/amqp.go
Consuming application is responsible for queue creation and its bindings.
=> amqp: removal of queue and binding creation

.github/workflows/main.yml, Dockerfile, scripts/docker-push.sh, scripts/package.sh
Would fix #628.
I've tried to keep as close as possible to the current workflow.
I added the `make package` step to have the builds for the various platform ready. I removed the line that deletes the build folders from the package script so that those artefacts can be reused by the docker build.
Finally building and pushing the docker containers is moved in a single step as the containers must be pushed directly by the buildx build.
I hope this will work in one go. I already tested the build but moved it out of the `if` condition in the script as I did not have the docker hub credentials setup.
=> Enables cross platform building and pushing of docker images

internal/endpoint/kafka.go
PR for #705.
I've confirmed it working against my companies AWS MSK cluster.
```
{ "time": "2023-09-08 16:18:19.7048", "level": "Error", "message": "[sarama] Initializing new client" }
{ "time": "2023-09-08 16:18:19.7048", "level": "Error", "message": "[sarama] ClientID is the default of 'sarama', you should consider setting it to something application-specific." }
{ "time": "2023-09-08 16:18:19.7048", "level": "Error", "message": "[sarama] ClientID is the default of 'sarama', you should consider setting it to something application-specific." }
{ "time": "2023-09-08 16:18:19.7048", "level": "Error", "message": "[sarama] client/metadata fetching metadata for all topics from broker b-1.dev-lab.jredk1.c13.kafka.us-west-2.amazonaws.com:9094" }
{ "time": "2023-09-08 16:18:19.7054", "level": …
```
=> Add support for 'none' authentication for kafka while still allowing SSL

internal/endpoint/sqs.go
For AWS China region base domain is slightly different than for the rest world. It is `amazon.com.cn`.
Currently AWS domain is hard coded in the `sqs.go`. Would be nice if that will be configured parameter.
But this is a minimal possible change which is not breaking exist code and make possible to use it for AWS China region.
=> [BUG] Fix AWS SQS base domain parsing for China region

internal/server/expire.go, internal/server/metrics.go
* `statsExpired` was never incremented
* `tile38_expired_keys` and some other metrics (seems like `tile38_total_messages_sent`) were never returned because `int64` values were never handled int Prometheus endpoint (`metrics.go`).
This is my first PR here and in Go. Apologies if something is not typical or idiomatic :-)
Feel free to close and rewrite if easier :-) Mostly wanted to illustrate the cause of the issue, as I understand it.
Fixes https://github.com/tidwall/tile38/issues/717
=> fix #717: tile38_expired_keys and several other metrics not returned

README.md, core/commands.json, core/commands_gen.go, internal/server/crud.go, internal/server/scripts.go, internal/server/server.go, tests/keys_test.go
Please do not open a pull request without first filing an issue and/or discussing the feature directly with the project maintainer.
Adds new command `FGET key id field` which allows for getting just a single field value
https://github.com/tidwall/tile38/issues/723
=> Add FGET command

core/commands.json, core/commands_gen.go, internal/server/crud.go, internal/server/scripts.go, internal/server/server.go, tests/keys_test.go
Add support for
```
EXISTS key id
```
and 
```
FEXISTS key id field
```
https://github.com/tidwall/tile38/issues/722
=> Add EXIST and FEXIST command

internal/server/server.go, tests/proto_test.go, tests/tests_test.go
Please do not open a pull request without first filing an issue and/or discussing the feature directly with the project maintainer.
Adds support for OPTIONS HTTP request and returns necessary headers to allow CORS to function properly
https://github.com/tidwall/tile38/issues/737
I'm not quite sure how testing should be performed here as I don't see any testing of the http interface right now.. maybe i'm missing something. Could use a pointer on where and how you'd like me to write tests. 
Tests can be done with standard HTTP requests.
=> Add support for CORS in http requests

internal/server/crud.go, tests/keys_test.go
Figured it is minor enough to not wait your okay on this @tidwall . :pray: 
moving the `string.ToLower()` conversion into the switch statement instead of mutating the input argument ensures field cases are preserved. added additional tests.
```go
[...]
for i := 3; i < len(args); i++ {
arg := args[i]
switch strings.ToLower(arg) {
case "xx":
xx = true
default:
fkey := arg
i++
[...]
```
fixes #741
=> fix: FSET lowercasing upper case fields

internal/server/token.go, internal/server/token_test.go, tests/keys_test.go
fixes #741 
field names where `WHEREIN` queries were changed to lower case causing unexpected behaviour as outlined in #741. I removed `strings.ToLower()` and added a few tests around the behaviour.
=> fix: whereins defaulting to lower case

internal/server/stats.go
This adds support for `slave_repl_offset` to the `INFO REPLICATION` command.
I just grabbed the `int(s.faofsz)` from here (output of the `ROLE` command). Can you confirm this would be the right stat to grab? I don't really see where this gets updated.  I guess i could have just used the `s.aofsz` which does get updated...  
For my purposes, i guess as long as its not 0 it should fix my problem.
https://github.com/tidwall/tile38/blob/a953466318ce1d65a16259099a5b023650bfdf11/internal/server/stats.go#L633-L639
This fixes #750
=> Add 'slave_repl_offset' to the INFO replication command output

internal/endpoint/sqs.go
Please do not open a pull request without first filing an issue and/or discussing the feature directly with the project maintainer.
All SQS FIFO queues have the `.fifo` suffix at the end of their URL - this is how we determine if we are using a FIFO queue or not. The `MessageGroupId` (A required field for FIFO) is set using the key & id of the event's message.
Note: This commit does not add the the `MessageDeduplicationID` so the FIFO queue must have content-based deduplication enabled.
https://github.com/tidwall/tile38/issues/758
=> Adds the ability to use SQS FIFO queues.

Dockerfile
In another project, we had these Trivy findings for `tile38/tile38:1.33.4`:
```
[CVE-2024-0727]    libcrypto1.1    1.1.1w-r1
[CVE-2024-0727]    libssl1.1       1.1.1w-r1
```
[CVE-2024-0727](https://nvd.nist.gov/vuln/detail/cve-2024-0727) targets `openssl 1.1.1` (including) - `1.1.1x` (excluding)
* [Additional source](https://security.alpinelinux.org/vuln/CVE-2024-0727)
For `alpine:3.16.2`, it seems like the latest, supported version of openssl is `1.1.1w`.
=> Upgrade base image in Dockerfile to alpine:3.20

go.mod, go.sum
In another project, we had a Trivy finding for `tile38/tile38:1.34.0`:
```
[CVE-2024-45338] golang.org/x/net:v0.23.0
```
[CVE-2024-45338](https://github.com/advisories/GHSA-w32m-9786-jp63) targets `golang.org/x/net` < `0.33.0`
=> Bump golang.org/x/net from v0.23.0 to v0.33.0

go.mod, go.sum, internal/endpoint/kafka.go
Kafka Endpoint improvements, dependency update, support for Kafka 4.0+
Please do not open a pull request without first filing an issue and/or discussing the feature directly with the project maintainer.
Upgraded the Sarama package to the latest [1.46.0](https://github.com/IBM/sarama/releases/tag/v1.46.0) that enables client API selection from the broker version. This handles backward compatibility and enables the correct Api version selection for 4.0+
[777](https://github.com/tidwall/tile38/issues/777)
=> Kafka Endpoint Improvement (Kafka 4.0+ Support)
