tidwall/tile38

geojson/geohash/geohash_test.go
Hi,
I have added some (hopefully) useful test cases for geohash.go.
=> Added test cases

controller/fence.go, controller/scan.go, controller/scanner.go, controller/search.go, controller/token.go, core/commands.json, core/commands_gen.go
**Work in progress**
Implementing #112 feature.
Need to get some thoughts, @tidwall!
Idk, if i am doing this in way you wanna to make this feature up.
Btw, great tool! Love it a lot!
=> [WIP] Added distance to NEARBY command

controller/endpoint/disque.go
Fixed disque expiration timeout typo.
=> [FIX] Typo fix

controller/live.go
Related issue #118 
@tidwall but i think we should also handle connection close properly and after this unexpected EOF close websocket connection, not just by timeout ⌛️
=> Fixed [Unexpected] EOF bug with websockets

controller/config.go, controller/controller.go
@tidwall, review please.
Resolving: #133 
**TODO:** `documentation`
=> Implementing autogc configuration support

pkg/endpoint/kafka.go
Pull request related to issue #333
=> fix #333 : regression bug introduced by sarama library

pkg/endpoint/nats.go
Hi,
I forgot an else statement... And could you please push the newest version to the docker hub ? Would be nice.
=> fixed missing else statement when creating nats connection

pkg/core/commands.json
Add previously undocumented argument `STR`.
See the related doc PR at: https://github.com/tile38/tile38.github.io/pull/19
=> Update JSET arguments

Gopkg.lock, internal/server/search.go, vendor/github.com/tidwall/geojson/circle.go, vendor/github.com/tidwall/geojson/circle_test.go, vendor/github.com/tidwall/geojson/geo/geo.go, vendor/github.com/tidwall/geojson/geo/geo_test.go
This needs new geojson package.
Once https://github.com/tidwall/geojson/pull/4 merges  I can add necessary changes here.
=> Use haversine instead of distance in knn if distance is not required.

internal/server/scripts.go, tests/scripts_test.go
`distance_to(lat_a, lon_a, lat_b, lon_b)` returns distance in meters between points A and B.
=> Add distance_to function to the tile38 namespace in lua.

internal/server/keys.go, tests/keys_test.go
=> Fixing KEYS command and tests

Gopkg.lock, build.sh, vendor/github.com/tidwall/evio/internal/internal_linux.go, vendor/github.com/tidwall/geojson/geometry/series.go
=> Adding ARM and ARM64 packages

internal/server/client.go, internal/server/stats.go, tests/client_test.go, tests/stats_test.go, tests/tests_test.go
=> JSON Output for INFO and CLIENT

internal/endpoint/http.go
=> Allow 201 & 202 status code on webhooks

Gopkg.lock, Gopkg.toml, vendor/github.com/tidwall/geojson/circle.go, vendor/github.com/tidwall/geojson/circle_test.go, vendor/github.com/tidwall/geojson/object.go, vendor/github.com/tidwall/geojson/point.go, vendor/github.com/tidwall/geojson/simplepoint.go, vendor/github.com/tidwall/geojson/simplepoint_test.go
=> Fixed nearby inaccuracy with geofence

internal/server/hooks.go
=> Fixed clients blocking while webook sending

tests/client_test.go, tests/mock_test.go
=> Removed elapsed member for json testing

internal/server/scanner.go, tests/keys_search_test.go
This fixes the problem described in issue #453.
=> Fix json nearby fields

internal/server/pubsub.go
=> Added unsubscribing from active channel

Gopkg.lock, Gopkg.toml, vendor/github.com/tidwall/geojson/geo/geo.go, vendor/github.com/tidwall/geojson/geo/geo_test.go
=> Updated geojson

internal/server/scripts.go
Fixes https://github.com/tidwall/tile38/issues/482
=> Fix lua pool pruning

.travis.yml
Move Travis ci to test with 1.13
=> Update travis-ci to Go 1.13

internal/server/aofshrink.go
=> Fixed panic on AOFSHRINK

internal/server/fence.go
=> Fixed DEL geofence notifications missing "key" field

internal/clip/clip_test.go
This must have slipped through the cracks when geo Index Options PR was re-done, #545
=> Fix clip test after geoOptions change.

internal/collection/collection.go, internal/collection/collection_test.go, internal/collection/fieldvalues.go
See #547 for details an motivation
=> Optimize field value access

cmd/tile38-server/main.go
minor residue from another approach I noticed too late
=> docs: remove --logjson flag from usage

internal/server/scanner.go, tests/keys_search_test.go
=> feat: add distance to NEARBY IDS response

internal/server/server.go
=> Add auth to allowed commands while data is loading

README.md, internal/endpoint/local.go, internal/field/field.go, internal/field/list_binary.go, internal/server/checksum.go, internal/server/server.go, tests/README.md
fix some typos in comments
Pull request require a prior issue with discussion. 
Include the issue number of link here.
=> chore: fix some typos in comments

internal/server/stats.go
Fixes: https://github.com/tidwall/tile38/issues/748
=> Remove extra quote in ROLE command with JSON output
